baseURL = "/"
languageCode = "en-us"
title = "Software Developer"
theme = "anatole"
enableEmoji = true
enableGitInfo = true
summarylength = 10

[params]
title = "I'm Marc"
author = "CodeHat"
description = "Software Developer"
profilePicture = "images/profile.png"
favicon = "favicons/"
doNotLoadAnimations = true
enableRobotsTXT = true
contentratio = 0.7
mainSections = []
postSectionName = "blog"
googleFonts = [
  "Ubuntu"
]
customCss = [
  "css/styles.css"
]

[params.plausibleAnalytics]
domain = "codehat.de"
serverURL = "https://analytics.thisismy.cloud"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "E-Mail"
url = "mailto:dev@codehat.de"

[[params.socialIcons]]
icon = "fas fa-key"
title = "PGP Key"
url = "/CodeHat_0xA0D21575_public.asc"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/kodehat/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/CodeHat/"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "Version"
  weight = 300
  identifier = "version"
  url = "/version/"

  [[menu.main]]
  name = "Legal Details"
  weight = 400
  identifier = "legal-details"
  url = "/legal-details/"