baseURL = "/"
languageCode = "en-us"
title = "Software Developer"
theme = "anatole"
enableEmoji = true
enableGitInfo = true
summarylength = 10

[outputs]
home = ["HTML"]
section = ["HTML", "RSS"]
taxonomy = ["HTML"]
term = ["HTML"]

[params]
title = "I'm CodeHat"
author = "CodeHat"
description = """
Call me Marc
Software Developer
"""
profilePicture = "images/profile.png"
favicon = "favicons/"
doNotLoadAnimations = true
enableRobotsTXT = true
contentratio = 0.7
mainSections = []
postSectionName = "blog"
rssFullContent = true
#googleFonts = [
#  "Roboto+Slab:wght@100;400;700"
#]
customCss = [
  "css/styles.css"
]
gitUrl = "https://github.com/kodehat/codehat.de"

[params.plausibleAnalytics]
domain = "codehat.de"
serverURL = "https://analytics.thisismy.cloud"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "E-Mail"
url = "mailto:dev@codehat.de"

[[params.socialIcons]]
icon = "fas fa-key"
title = "PGP Key"
url = "/CodeHat_0xA0D21575_public.asc"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/kodehat/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/CodeHat/"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "Projects"
  weight = 300
  identifier = "projects"
  url = "/projects/"

  [[menu.main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/contact/"

  [[menu.footer]]
  name = "Version"
  weight = 100
  identifier = "version"
  url = "/version/"

  [[menu.footer]]
  name = "Legal Details"
  weight = 200
  identifier = "legal-details"
  url = "/legal-details/"