baseURL = "/"
languageCode = "en-us"
title = "Software Developer"
theme = "anatole"
enableEmoji = true
summarylength = 10

[params]
title = "I'm CodeHat"
author = "CodeHat"
description = "Call me Marc"
profilePicture = "images/profile.png"
favicon = "favicons/"
doNotLoadAnimations = true
enableRobotsTXT = true
contentratio = 0.7
mainSections = []
googleFonts = [
  "Ubuntu"
]
customCss = [
  "css/styles.css"
]

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "E-Mail"
url = "mailto:dev@codehat.de"

[[params.socialIcons]]
icon = "fas fa-key"
title = "PGP Key"
url = "/CodeHat_0xA0D21575_public.asc"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/kodehat/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/CodeHat/"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Legal Details"
  weight = 400
  identifier = "legal-details"
  url = "/legal-details/"